// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

#ifndef PROTOBUF_protocol_2eproto__INCLUDED
#define PROTOBUF_protocol_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_protocol_2eproto();
void protobuf_AssignDesc_protocol_2eproto();
void protobuf_ShutdownFile_protocol_2eproto();

class Book;
class Student;

// ===================================================================

class Book : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Book) */ {
 public:
  Book();
  virtual ~Book();

  Book(const Book& from);

  inline Book& operator=(const Book& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Book& default_instance();

  void Swap(Book* other);

  // implements Message ----------------------------------------------

  inline Book* New() const { return New(NULL); }

  Book* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Book& from);
  void MergeFrom(const Book& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Book* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional int32 pages = 2;
  bool has_pages() const;
  void clear_pages();
  static const int kPagesFieldNumber = 2;
  ::google::protobuf::int32 pages() const;
  void set_pages(::google::protobuf::int32 value);

  // optional float price = 3;
  bool has_price() const;
  void clear_price();
  static const int kPriceFieldNumber = 3;
  float price() const;
  void set_price(float value);

  // @@protoc_insertion_point(class_scope:Book)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_pages();
  inline void clear_has_pages();
  inline void set_has_price();
  inline void clear_has_price();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::int32 pages_;
  float price_;
  friend void  protobuf_AddDesc_protocol_2eproto();
  friend void protobuf_AssignDesc_protocol_2eproto();
  friend void protobuf_ShutdownFile_protocol_2eproto();

  void InitAsDefaultInstance();
  static Book* default_instance_;
};
// -------------------------------------------------------------------

class Student : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Student) */ {
 public:
  Student();
  virtual ~Student();

  Student(const Student& from);

  inline Student& operator=(const Student& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Student& default_instance();

  void Swap(Student* other);

  // implements Message ----------------------------------------------

  inline Student* New() const { return New(NULL); }

  Student* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Student& from);
  void MergeFrom(const Student& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Student* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 age = 1;
  bool has_age() const;
  void clear_age();
  static const int kAgeFieldNumber = 1;
  ::google::protobuf::int32 age() const;
  void set_age(::google::protobuf::int32 value);

  // optional string name = 2;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional float score = 3;
  bool has_score() const;
  void clear_score();
  static const int kScoreFieldNumber = 3;
  float score() const;
  void set_score(float value);

  // repeated .Book arrBook = 4;
  int arrbook_size() const;
  void clear_arrbook();
  static const int kArrBookFieldNumber = 4;
  const ::Book& arrbook(int index) const;
  ::Book* mutable_arrbook(int index);
  ::Book* add_arrbook();
  ::google::protobuf::RepeatedPtrField< ::Book >*
      mutable_arrbook();
  const ::google::protobuf::RepeatedPtrField< ::Book >&
      arrbook() const;

  // @@protoc_insertion_point(class_scope:Student)
 private:
  inline void set_has_age();
  inline void clear_has_age();
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_score();
  inline void clear_has_score();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::int32 age_;
  float score_;
  ::google::protobuf::RepeatedPtrField< ::Book > arrbook_;
  friend void  protobuf_AddDesc_protocol_2eproto();
  friend void protobuf_AssignDesc_protocol_2eproto();
  friend void protobuf_ShutdownFile_protocol_2eproto();

  void InitAsDefaultInstance();
  static Student* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Book

// optional string name = 1;
inline bool Book::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Book::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Book::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Book::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& Book::name() const {
  // @@protoc_insertion_point(field_get:Book.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Book::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Book.name)
}
inline void Book::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Book.name)
}
inline void Book::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Book.name)
}
inline ::std::string* Book::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:Book.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Book::release_name() {
  // @@protoc_insertion_point(field_release:Book.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Book::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:Book.name)
}

// optional int32 pages = 2;
inline bool Book::has_pages() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Book::set_has_pages() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Book::clear_has_pages() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Book::clear_pages() {
  pages_ = 0;
  clear_has_pages();
}
inline ::google::protobuf::int32 Book::pages() const {
  // @@protoc_insertion_point(field_get:Book.pages)
  return pages_;
}
inline void Book::set_pages(::google::protobuf::int32 value) {
  set_has_pages();
  pages_ = value;
  // @@protoc_insertion_point(field_set:Book.pages)
}

// optional float price = 3;
inline bool Book::has_price() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Book::set_has_price() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Book::clear_has_price() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Book::clear_price() {
  price_ = 0;
  clear_has_price();
}
inline float Book::price() const {
  // @@protoc_insertion_point(field_get:Book.price)
  return price_;
}
inline void Book::set_price(float value) {
  set_has_price();
  price_ = value;
  // @@protoc_insertion_point(field_set:Book.price)
}

// -------------------------------------------------------------------

// Student

// optional int32 age = 1;
inline bool Student::has_age() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Student::set_has_age() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Student::clear_has_age() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Student::clear_age() {
  age_ = 0;
  clear_has_age();
}
inline ::google::protobuf::int32 Student::age() const {
  // @@protoc_insertion_point(field_get:Student.age)
  return age_;
}
inline void Student::set_age(::google::protobuf::int32 value) {
  set_has_age();
  age_ = value;
  // @@protoc_insertion_point(field_set:Student.age)
}

// optional string name = 2;
inline bool Student::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Student::set_has_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Student::clear_has_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Student::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& Student::name() const {
  // @@protoc_insertion_point(field_get:Student.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Student::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Student.name)
}
inline void Student::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Student.name)
}
inline void Student::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Student.name)
}
inline ::std::string* Student::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:Student.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Student::release_name() {
  // @@protoc_insertion_point(field_release:Student.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Student::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:Student.name)
}

// optional float score = 3;
inline bool Student::has_score() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Student::set_has_score() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Student::clear_has_score() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Student::clear_score() {
  score_ = 0;
  clear_has_score();
}
inline float Student::score() const {
  // @@protoc_insertion_point(field_get:Student.score)
  return score_;
}
inline void Student::set_score(float value) {
  set_has_score();
  score_ = value;
  // @@protoc_insertion_point(field_set:Student.score)
}

// repeated .Book arrBook = 4;
inline int Student::arrbook_size() const {
  return arrbook_.size();
}
inline void Student::clear_arrbook() {
  arrbook_.Clear();
}
inline const ::Book& Student::arrbook(int index) const {
  // @@protoc_insertion_point(field_get:Student.arrBook)
  return arrbook_.Get(index);
}
inline ::Book* Student::mutable_arrbook(int index) {
  // @@protoc_insertion_point(field_mutable:Student.arrBook)
  return arrbook_.Mutable(index);
}
inline ::Book* Student::add_arrbook() {
  // @@protoc_insertion_point(field_add:Student.arrBook)
  return arrbook_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Book >*
Student::mutable_arrbook() {
  // @@protoc_insertion_point(field_mutable_list:Student.arrBook)
  return &arrbook_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Book >&
Student::arrbook() const {
  // @@protoc_insertion_point(field_list:Student.arrBook)
  return arrbook_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_protocol_2eproto__INCLUDED
